version: '3'
services:
    web:
        build: ./flask
        context: ./flask
        dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./flask:/flask
        restart: always
